name: tutorial_gcPCA
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pip
  - pip:
      - generalized-contrastive-pca
      - marimo
      - jupyter
